/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { JSX, useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js';

type GLTFResult = GLTF & {
  nodes: {
    dolmen1001: THREE.Mesh;
    dolmen1: THREE.Mesh;
    dolmen1002: THREE.Mesh;
    dolmen1003_1: THREE.Mesh;
    dolmen1004: THREE.Mesh;
    dolmen1005: THREE.Mesh;
    dolmen1006: THREE.Mesh;
    dolmen1007: THREE.Mesh;
    dolmen1008: THREE.Mesh;
    dolmen1009: THREE.Mesh;
    dolmen1010: THREE.Mesh;
    dolmen1011: THREE.Mesh;
    dolmen1012: THREE.Mesh;
    dolmen1013: THREE.Mesh;
    dolmen1014: THREE.Mesh;
    dolmen1015: THREE.Mesh;
    dolmen1016: THREE.Mesh;
    dolmen1017: THREE.Mesh;
    dolmen1018: THREE.Mesh;
    dolmen1019: THREE.Mesh;
    dolmen1020: THREE.Mesh;
    dolmen2: THREE.Mesh;
    dolmen2001: THREE.Mesh;
    dolmen2002: THREE.Mesh;
    dolmen2003: THREE.Mesh;
    dolmen2004: THREE.Mesh;
    dolmen2005: THREE.Mesh;
    dolmen3: THREE.Mesh;
    dolmen3001: THREE.Mesh;
    dolmen3002: THREE.Mesh;
    dolmen4: THREE.Mesh;
    dolmen4001: THREE.Mesh;
    dolmen4002: THREE.Mesh;
    dolmen4003: THREE.Mesh;
    dolmen4004: THREE.Mesh;
    dolmen4005: THREE.Mesh;
    dolmen4006: THREE.Mesh;
    dolmen4007: THREE.Mesh;
    dolmen4008: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
    Material_1: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null);
  const { nodes } = useGLTF(
    'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/cromlech/model.gltf'
  ) as unknown as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.dolmen1001.geometry}
        material={nodes.dolmen1001.material}
      >
        <mesh
          geometry={nodes.dolmen1.geometry}
          material={nodes.dolmen1.material}
        />
        <mesh
          geometry={nodes.dolmen1002.geometry}
          material={nodes.dolmen1002.material}
        />
        <mesh
          geometry={nodes.dolmen1003_1.geometry}
          material={nodes.dolmen1003_1.material}
        />
        <mesh
          geometry={nodes.dolmen1004.geometry}
          material={nodes.dolmen1004.material}
        />
        <mesh
          geometry={nodes.dolmen1005.geometry}
          material={nodes.dolmen1005.material}
        />
        <mesh
          geometry={nodes.dolmen1006.geometry}
          material={nodes.dolmen1006.material}
        />
        <mesh
          geometry={nodes.dolmen1007.geometry}
          material={nodes.dolmen1007.material}
        />
        <mesh
          geometry={nodes.dolmen1008.geometry}
          material={nodes.dolmen1008.material}
        />
        <mesh
          geometry={nodes.dolmen1009.geometry}
          material={nodes.dolmen1009.material}
        />
        <mesh
          geometry={nodes.dolmen1010.geometry}
          material={nodes.dolmen1010.material}
        />
        <mesh
          geometry={nodes.dolmen1011.geometry}
          material={nodes.dolmen1011.material}
        />
        <mesh
          geometry={nodes.dolmen1012.geometry}
          material={nodes.dolmen1012.material}
        />
        <mesh
          geometry={nodes.dolmen1013.geometry}
          material={nodes.dolmen1013.material}
        />
        <mesh
          geometry={nodes.dolmen1014.geometry}
          material={nodes.dolmen1014.material}
        />
        <mesh
          geometry={nodes.dolmen1015.geometry}
          material={nodes.dolmen1015.material}
        />
        <mesh
          geometry={nodes.dolmen1016.geometry}
          material={nodes.dolmen1016.material}
        />
        <mesh
          geometry={nodes.dolmen1017.geometry}
          material={nodes.dolmen1017.material}
        />
        <mesh
          geometry={nodes.dolmen1018.geometry}
          material={nodes.dolmen1018.material}
        />
        <mesh
          geometry={nodes.dolmen1019.geometry}
          material={nodes.dolmen1019.material}
        />
        <mesh
          geometry={nodes.dolmen1020.geometry}
          material={nodes.dolmen1020.material}
        />
        <mesh
          geometry={nodes.dolmen2.geometry}
          material={nodes.dolmen2.material}
        />
        <mesh
          geometry={nodes.dolmen2001.geometry}
          material={nodes.dolmen2001.material}
        />
        <mesh
          geometry={nodes.dolmen2002.geometry}
          material={nodes.dolmen2002.material}
        />
        <mesh
          geometry={nodes.dolmen2003.geometry}
          material={nodes.dolmen2003.material}
        />
        <mesh
          geometry={nodes.dolmen2004.geometry}
          material={nodes.dolmen2004.material}
        />
        <mesh
          geometry={nodes.dolmen2005.geometry}
          material={nodes.dolmen2005.material}
        />
        <mesh
          geometry={nodes.dolmen3.geometry}
          material={nodes.dolmen3.material}
        />
        <mesh
          geometry={nodes.dolmen3001.geometry}
          material={nodes.dolmen3001.material}
        />
        <mesh
          geometry={nodes.dolmen3002.geometry}
          material={nodes.dolmen3002.material}
        />
        <mesh
          geometry={nodes.dolmen4.geometry}
          material={nodes.dolmen4.material}
        />
        <mesh
          geometry={nodes.dolmen4001.geometry}
          material={nodes.dolmen4001.material}
        />
        <mesh
          geometry={nodes.dolmen4002.geometry}
          material={nodes.dolmen4002.material}
        />
        <mesh
          geometry={nodes.dolmen4003.geometry}
          material={nodes.dolmen4003.material}
        />
        <mesh
          geometry={nodes.dolmen4004.geometry}
          material={nodes.dolmen4004.material}
        />
        <mesh
          geometry={nodes.dolmen4005.geometry}
          material={nodes.dolmen4005.material}
        />
        <mesh
          geometry={nodes.dolmen4006.geometry}
          material={nodes.dolmen4006.material}
        />
        <mesh
          geometry={nodes.dolmen4007.geometry}
          material={nodes.dolmen4007.material}
        />
        <mesh
          geometry={nodes.dolmen4008.geometry}
          material={nodes.dolmen4008.material}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload(
  'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/cromlech/model.gltf'
);
