/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef, JSX } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js';

type GLTFResult = GLTF & {
  nodes: {
    Mesh_house_type08: THREE.Mesh;
    Mesh_house_type08_1: THREE.Mesh;
    Mesh_house_type08_2: THREE.Mesh;
    Mesh_house_type08_3: THREE.Mesh;
    Mesh_house_type08_4: THREE.Mesh;
  };
  materials: {
    border: THREE.MeshStandardMaterial;
    window: THREE.MeshStandardMaterial;
    main: THREE.MeshStandardMaterial;
    roof: THREE.MeshStandardMaterial;
    door: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF(
    'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/house-5/model.gltf'
  ) as unknown as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_house_type08.geometry}
        material={materials.border}
      />
      <mesh
        geometry={nodes.Mesh_house_type08_1.geometry}
        material={materials.window}
      />
      <mesh
        geometry={nodes.Mesh_house_type08_2.geometry}
        material={materials.main}
      />
      <mesh
        geometry={nodes.Mesh_house_type08_3.geometry}
        material={materials.roof}
      />
      <mesh
        geometry={nodes.Mesh_house_type08_4.geometry}
        material={materials.door}
      />
    </group>
  );
}

useGLTF.preload(
  'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/house-5/model.gltf'
);
