/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { JSX, useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js';

type GLTFResult = GLTF & {
  nodes: {
    Mesh_house_type03: THREE.Mesh;
    Mesh_house_type03_1: THREE.Mesh;
    Mesh_house_type03_2: THREE.Mesh;
    Mesh_house_type03_3: THREE.Mesh;
    Mesh_house_type03_4: THREE.Mesh;
  };
  materials: {
    ['border.003']: THREE.MeshStandardMaterial;
    ['window.003']: THREE.MeshStandardMaterial;
    ['door.003']: THREE.MeshStandardMaterial;
    ['_defaultMat.003']: THREE.MeshStandardMaterial;
    ['roof.005']: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF(
    'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/house-3/model.gltf'
  ) as unknown as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_house_type03.geometry}
        material={materials['border.003']}
      />
      <mesh
        geometry={nodes.Mesh_house_type03_1.geometry}
        material={materials['window.003']}
      />
      <mesh
        geometry={nodes.Mesh_house_type03_2.geometry}
        material={materials['door.003']}
      />
      <mesh
        geometry={nodes.Mesh_house_type03_3.geometry}
        material={materials['_defaultMat.003']}
      />
      <mesh
        geometry={nodes.Mesh_house_type03_4.geometry}
        material={materials['roof.005']}
      />
    </group>
  );
}

useGLTF.preload(
  'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/house-3/model.gltf'
);
