/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { JSX, useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js';

type GLTFResult = GLTF & {
  nodes: {
    formationLarge_rock_1: THREE.Mesh;
    formationLarge_rock_2: THREE.Mesh;
  };
  materials: {
    ['wood.009']: THREE.MeshStandardMaterial;
    ['sand.001']: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF(
    'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/formation-large-rock/model.gltf'
  ) as unknown as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[4.05, 0, -10.64]} scale={[1, 0.77, 1]}>
        <mesh
          geometry={nodes.formationLarge_rock_1.geometry}
          material={materials['wood.009']}
        />
        <mesh
          geometry={nodes.formationLarge_rock_2.geometry}
          material={materials['sand.001']}
        />
      </group>
    </group>
  );
}

useGLTF.preload(
  'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/formation-large-rock/model.gltf'
);
