/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef, JSX } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js';

type GLTFResult = GLTF & {
  nodes: {
    Cube049: THREE.Mesh;
    Cube049_1: THREE.Mesh;
  };
  materials: {
    lightGrey: THREE.MeshStandardMaterial;
    Grey: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF(
    'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/ruins/model.gltf'
  ) as unknown as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[207.75, 1.48, -4.36]} scale={[0.31, 0.27, 0.31]}>
        <mesh
          geometry={nodes.Cube049.geometry}
          material={materials.lightGrey}
        />
        <mesh geometry={nodes.Cube049_1.geometry} material={materials.Grey} />
      </group>
    </group>
  );
}

useGLTF.preload(
  'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/ruins/model.gltf'
);
