/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef, JSX } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js';

type GLTFResult = GLTF & {
  nodes: {
    tower_1: THREE.Mesh;
    tower_2: THREE.Mesh;
    tower_3: THREE.Mesh;
    tower_4: THREE.Mesh;
    tower_5: THREE.Mesh;
    tower_6: THREE.Mesh;
    tower_7: THREE.Mesh;
  };
  materials: {
    ['stone.006']: THREE.MeshStandardMaterial;
    ['woodDark.003']: THREE.MeshStandardMaterial;
    ['_defaultMat.007']: THREE.MeshStandardMaterial;
    ['iron.011']: THREE.MeshStandardMaterial;
    ['wood.024']: THREE.MeshStandardMaterial;
    ['sand.006']: THREE.MeshStandardMaterial;
    ['textile.008']: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF(
    'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/tower/model.gltf'
  ) as unknown as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-5.51, 0, -1.63]}>
        <mesh
          geometry={nodes.tower_1.geometry}
          material={materials['stone.006']}
        />
        <mesh
          geometry={nodes.tower_2.geometry}
          material={materials['woodDark.003']}
        />
        <mesh
          geometry={nodes.tower_3.geometry}
          material={materials['_defaultMat.007']}
        />
        <mesh
          geometry={nodes.tower_4.geometry}
          material={materials['iron.011']}
        />
        <mesh
          geometry={nodes.tower_5.geometry}
          material={materials['wood.024']}
        />
        <mesh
          geometry={nodes.tower_6.geometry}
          material={materials['sand.006']}
        />
        <mesh
          geometry={nodes.tower_7.geometry}
          material={materials['textile.008']}
        />
      </group>
    </group>
  );
}

useGLTF.preload(
  'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/tower/model.gltf'
);
