/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { JSX, useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js';

type GLTFResult = GLTF & {
  nodes: {
    Wind_turbine_001_Wind_turbine_Circle001: THREE.Mesh;
    Wind_turbine_001_Wind_turbine_Circle001_1: THREE.Mesh;
    Wind_turbine_001_Wind_turbine_Circle000: THREE.Mesh;
    Wind_turbine_001_Wind_turbine_Circle000_1: THREE.Mesh;
  };
  materials: {
    gray: THREE.MeshStandardMaterial;
    red: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null);
  const { nodes } = useGLTF(
    'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/wind-turbine/model.gltf'
  ) as unknown as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Wind_turbine_001'>
        <mesh
          geometry={nodes.Wind_turbine_001_Wind_turbine_Circle001.geometry}
          material={nodes.Wind_turbine_001_Wind_turbine_Circle001.material}
        />
        <mesh
          geometry={nodes.Wind_turbine_001_Wind_turbine_Circle001_1.geometry}
          material={nodes.Wind_turbine_001_Wind_turbine_Circle001_1.material}
        />
        <group name='Wind_turbine_001_Blades' position={[0.01, 4.38, 0.49]}>
          <mesh
            geometry={nodes.Wind_turbine_001_Wind_turbine_Circle000.geometry}
            material={nodes.Wind_turbine_001_Wind_turbine_Circle000.material}
          />
          <mesh
            geometry={nodes.Wind_turbine_001_Wind_turbine_Circle000_1.geometry}
            material={nodes.Wind_turbine_001_Wind_turbine_Circle000_1.material}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(
  'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/wind-turbine/model.gltf'
);
